import WC2022Team from "../../models/sport/football/2022-fifa-world-cup/WC2022Team";

const WC_2022_INITIAL_TEAM_SEEDS: WC2022Team[] = [
  {
    name: "Qatar",
    isHost: true,
    code: "",
    group: "A",
    flag: "", //replace with url, use storage?
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Ecuador",
    isHost: false,
    code: "",
    group: "A",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Senegal",
    isHost: false,
    code: "",
    group: "A",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Netherlands",
    isHost: false,
    code: "",
    group: "A",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "England",
    isHost: false,
    code: "ENG",
    group: "B",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Iran",
    isHost: false,
    code: "",
    group: "B",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "United States",
    isHost: false,
    code: "USA",
    group: "B",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Wales",
    isHost: false,
    code: "",
    group: "B",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Mexico",
    isHost: false,
    code: "",
    group: "C",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Poland",
    isHost: false,
    code: "",
    group: "C",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Argentina",
    isHost: false,
    code: "",
    group: "C",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Saudi Arabia",
    isHost: false,
    code: "",
    group: "C",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "France",
    isHost: false,
    code: "",
    group: "D",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Australia",
    isHost: false,
    code: "",
    group: "D",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Denmark",
    isHost: false,
    code: "",
    group: "D",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Tunisia",
    isHost: false,
    code: "",
    group: "D",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Spain",
    isHost: false,
    code: "",
    group: "E",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Costa Rica",
    isHost: false,
    code: "",
    group: "E",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Germany",
    isHost: false,
    code: "",
    group: "E",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Japan",
    isHost: false,
    code: "",
    group: "E",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Belgium",
    isHost: false,
    code: "",
    group: "F",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Canada",
    isHost: false,
    code: "",
    group: "F",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Morocco",
    isHost: false,
    code: "",
    group: "F",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Croatia",
    isHost: false,
    code: "",
    group: "F",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Switzerland",
    isHost: false,
    code: "",
    group: "G",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Cameroon",
    isHost: false,
    code: "",
    group: "G",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Brazil",
    isHost: false,
    code: "",
    group: "G",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Spain",
    isHost: false,
    code: "",
    group: "G",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Uruguay",
    isHost: false,
    code: "",
    group: "H",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "South Korea",
    isHost: false,
    code: "",
    group: "H",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Portugal",
    isHost: false,
    code: "",
    group: "H",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
  {
    name: "Ghana",
    isHost: false,
    code: "",
    group: "H",
    flag: "",
    finalStanding: "TBA",
    groupStageGoalsFor: 0,
    groupStageGoalsAgainst: 0,
    groupStageMatchesPlayed: 0,
    groupStageWins: 0,
    groupStageLoses: 0,
    groupStageDraws: 0,
  },
];

export default WC_2022_INITIAL_TEAM_SEEDS;
