import {
  WC2022FinalMatch,
  WC2022GroupMatch,
  WC2022QFMatch,
  WC2022R16Match,
  WC2022SFMatch,
  WC2022ThirdPlaceMatch,
} from "../../models/sport/football/2022-fifa-world-cup/WC2022Match";

// TODO: Fix and then use Match interface in /models
export const WC_2022_MATCH_SEEDS_GROUP_STAGE: WC2022GroupMatch[] = [
  {
    matchNumber: 1,
    round: "Group Stage",
    team1: "Qatar",
    team2: "Ecuador",
    group: "A",
    date: new Date("2022 10 20"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 2,
    round: "Group Stage",
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    date: new Date("2022 10 21"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Thumama Stadium",
  },
  {
    matchNumber: 3,
    round: "Group Stage",
    team1: "England",
    team2: "Iran",
    group: "B",
    date: new Date("2022 10 21"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Khalifa International Stadium",
  },
  {
    matchNumber: 4,
    round: "Group Stage",
    team1: "United States",
    team2: "Wales",
    group: "B",
    date: new Date("2022 10 21"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 5,
    round: "Group Stage",
    team1: "France",
    team2: "Australia",
    group: "D",
    date: new Date("2022 10 22"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Janoub Stadium",
  },
  {
    matchNumber: 6,
    round: "Group Stage",
    team1: "Denmark",
    team2: "Tunisia",
    group: "D",
    date: new Date("2022 10 22"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 7,
    round: "Group Stage",
    team1: "Mexico",
    team2: "Argentina",
    group: "C",
    date: new Date("2022 10 22"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Stadium 974",
  },
  {
    matchNumber: 8,
    round: "Group Stage",
    team1: "Argentina",
    team2: "Saudi Arabia",
    group: "C",
    date: new Date("2022 10 22"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
  {
    matchNumber: 9,
    round: "Group Stage",
    team1: "Belgium",
    team2: "Canada",
    group: "F",
    date: new Date("2022 10 23"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 10,
    round: "Group Stage",
    team1: "Spain",
    team2: "Croatia",
    group: "E",
    date: new Date("2022 10 23"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Thumama Stadium",
  },
  {
    matchNumber: 11,
    round: "Group Stage",
    team1: "Germany",
    team2: "Japan",
    group: "E",
    date: new Date("2022 10 23"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Khalifa International Stadium",
  },
  {
    matchNumber: 12,
    round: "Group Stage",
    team1: "Morocco",
    team2: "Croatia",
    group: "F",
    date: new Date("2022 10 23"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 13,
    round: "Group Stage",
    team1: "Switzerland",
    team2: "Cameroon",
    group: "G",
    date: new Date("2022 10 24"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Janoub Stadium",
  },
  {
    matchNumber: 14,
    round: "Group Stage",
    team1: "Uruguay",
    team2: "South Korea",
    group: "H",
    date: new Date("2022 10 24"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 15,
    round: "Group Stage",
    team1: "Portugal",
    team2: "Ghana",
    group: "H",
    date: new Date("2022 10 24"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Stadium 974",
  },
  {
    matchNumber: 16,
    round: "Group Stage",
    team1: "Brazil",
    team2: "Serbia",
    group: "G",
    date: new Date("2022 10 24"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
  {
    matchNumber: 17,
    round: "Group Stage",
    team1: "Wales",
    team2: "Iran",
    group: "B",
    date: new Date("2022 10 25"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 18,
    round: "Group Stage",
    team1: "Qatar",
    team2: "Senegal",
    group: "A",
    date: new Date("2022 10 25"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Thumama Stadium",
  },
  {
    matchNumber: 19,
    round: "Group Stage",
    team1: "Netherlands",
    team2: "Ecuador",
    group: "A",
    date: new Date("2022 10 25"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Khalifa International Stadium",
  },
  {
    matchNumber: 20,
    round: "Group Stage",
    team1: "England",
    team2: "United States",
    group: "B",
    date: new Date("2022 10 25"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 21,
    round: "Group Stage",
    team1: "Tunisia",
    team2: "Australia",
    group: "D",
    date: new Date("2022 10 26"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Janoub Stadium",
  },
  {
    matchNumber: 22,
    round: "Group Stage",
    team1: "Poland",
    team2: "Saudi Arabia",
    group: "C",
    date: new Date("2022 10 26"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 23,
    round: "Group Stage",
    team1: "France",
    team2: "Denmark",
    group: "D",
    date: new Date("2022 10 26"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Stadium 974",
  },
  {
    matchNumber: 24,
    round: "Group Stage",
    team1: "Argentina",
    team2: "Mexico",
    group: "C",
    date: new Date("2022 10 26"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
  {
    matchNumber: 25,
    round: "Group Stage",
    team1: "Japan",
    team2: "Croatia",
    group: "E",
    date: new Date("2022 10 27"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 26,
    round: "Group Stage",
    team1: "Belgium",
    team2: "Morocco",
    group: "F",
    date: new Date("2022 10 27"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Thumama Stadium",
  },
  {
    matchNumber: 27,
    round: "Group Stage",
    team1: "Croatia",
    team2: "Canada",
    group: "F",
    date: new Date("2022 10 27"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Khalifa International Stadium",
  },
  {
    matchNumber: 28,
    round: "Group Stage",
    team1: "Morocco",
    team2: "Croatia",
    group: "E",
    date: new Date("2022 10 27"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 29,
    round: "Group Stage",
    team1: "Cameroon",
    team2: "Serbia",
    group: "G",
    date: new Date("2022 10 28"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Janoub Stadium",
  },
  {
    matchNumber: 30,
    round: "Group Stage",
    team1: "South Korea",
    team2: "Ghana",
    group: "H",
    date: new Date("2022 10 28"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 31,
    round: "Group Stage",
    team1: "Brazil",
    team2: "Switzerland",
    group: "G",
    date: new Date("2022 10 28"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Stadium 974",
  },
  {
    matchNumber: 32,
    round: "Group Stage",
    team1: "Portugal",
    team2: "Uruguay",
    group: "H",
    date: new Date("2022 10 28"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
  {
    matchNumber: 33,
    round: "Group Stage",
    team1: "Wales",
    team2: "England",
    group: "B",
    date: new Date("2022 10 29"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 34,
    round: "Group Stage",
    team1: "Iran",
    team2: "United States",
    group: "B",
    date: new Date("2022 10 29"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Thumama Stadium",
  },
  {
    matchNumber: 35,
    round: "Group Stage",
    team1: "Ecuador",
    team2: "Senegal",
    group: "A",
    date: new Date("2022 10 29"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Khalifa International Stadium",
  },
  {
    matchNumber: 36,
    round: "Group Stage",
    team1: "Netherlands",
    team2: "Qatar",
    group: "B",
    date: new Date("2022 10 29"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 37,
    round: "Group Stage",
    team1: "Australia",
    team2: "Denmark",
    group: "D",
    date: new Date("2022 10 30"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Janoub Stadium",
  },
  {
    matchNumber: 38,
    round: "Group Stage",
    team1: "Tunisia",
    team2: "France",
    group: "D",
    date: new Date("2022 10 30"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 39,
    round: "Group Stage",
    team1: "Poland",
    team2: "Argentina",
    group: "C",
    date: new Date("2022 10 30"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Stadium 974",
  },
  {
    matchNumber: 40,
    round: "Group Stage",
    team1: "Saudi Arabia",
    team2: "Mexico",
    group: "C",
    date: new Date("2022 10 30"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
  {
    matchNumber: 41,
    round: "Group Stage",
    team1: "Croatia",
    team2: "Belgium",
    group: "F",
    date: new Date("2022 11 1"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 42,
    round: "Group Stage",
    team1: "Canada",
    team2: "Morocco",
    group: "F",
    date: new Date("2022 11 1"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Thumama Stadium",
  },
  {
    matchNumber: 43,
    round: "Group Stage",
    team1: "Japan",
    team2: "Spain",
    group: "E",
    date: new Date("2022 11 1"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Khalifa International Stadium",
  },
  {
    matchNumber: 44,
    round: "Group Stage",
    team1: "Croatia",
    team2: "Germany",
    group: "E",
    date: new Date("2022 11 1"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 45,
    round: "Group Stage",
    team1: "Ghana",
    team2: "Uruguay",
    group: "H",
    date: new Date("2022 11 2"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Janoub Stadium",
  },
  {
    matchNumber: 30,
    round: "Group Stage",
    team1: "South Korea",
    team2: "Portugal",
    group: "H",
    date: new Date("2022 11 2"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 31,
    round: "Group Stage",
    team1: "Serbia",
    team2: "Switzerland",
    group: "G",
    date: new Date("2022 11 2"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Stadium 974",
  },
  {
    matchNumber: 32,
    round: "Group Stage",
    team1: "Cameroon",
    team2: "Brazil",
    group: "G",
    date: new Date("2022 11 2"),
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
];

export const WC_2022_MATCH_SEEDS_R16: WC2022R16Match[] = [
  {
    matchNumber: 49,
    round: "Round of 16",
    potentialTeam1: "1A",
    potentialTeam2: "2B",
    date: new Date("2022 11 3"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Khalifa International Stadium",
  },
  {
    matchNumber: 50,
    round: "Round of 16",
    potentialTeam1: "1C",
    potentialTeam2: "2D",
    date: new Date("2022 11 3"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 51,
    round: "Round of 16",
    potentialTeam1: "1B",
    potentialTeam2: "2A",
    date: new Date("2022 11 4"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 52,
    round: "Round of 16",
    potentialTeam1: "1D",
    potentialTeam2: "2C",
    date: new Date("2022 11 4"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Ahmad Bin Ali Stadium",
  },
  {
    matchNumber: 53,
    round: "Round of 16",
    potentialTeam1: "1E",
    potentialTeam2: "2F",
    date: new Date("2022 11 5"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Janoub Stadium",
  },
  {
    matchNumber: 54,
    round: "Round of 16",
    potentialTeam1: "1G",
    potentialTeam2: "2H",
    date: new Date("2022 11 5"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Stadium 974",
  },
  {
    matchNumber: 55,
    round: "Round of 16",
    potentialTeam1: "1F",
    potentialTeam2: "2E",
    date: new Date("2022 11 6"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 56,
    round: "Round of 16",
    potentialTeam1: "1H",
    potentialTeam2: "2G",
    date: new Date("2022 11 6"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
];

export const WC_2022_MATCH_SEEDS_QF: WC2022QFMatch[] = [
  {
    matchNumber: 57,
    round: "Quarter Final",
    potentialTeam1: "W49",
    potentialTeam2: "W50",
    date: new Date("2022 11 9"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
  {
    matchNumber: 58,
    round: "Quarter Final",
    potentialTeam1: "W53",
    potentialTeam2: "W54",
    date: new Date("2022 11 9"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Education City Stadium",
  },
  {
    matchNumber: 59,
    round: "Quarter Final",
    potentialTeam1: "W51",
    potentialTeam2: "W52",
    date: new Date("2022 11 10"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
  {
    matchNumber: 60,
    round: "Quarter Final",
    potentialTeam1: "W51",
    potentialTeam2: "W52",
    date: new Date("2022 11 10"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Thumama Stadium",
  },
];

export const WC_2022_MATCH_SEEDS_SF: WC2022SFMatch[] = [
  {
    matchNumber: 61,
    round: "Semi Final",
    potentialTeam1: "W57",
    potentialTeam2: "W58",
    date: new Date("2022 11 13"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Lusail Stadium",
  },
  {
    matchNumber: 62,
    round: "Semi Final",
    potentialTeam1: "W59",
    potentialTeam2: "W60",
    date: new Date("2022 11 14"),
    team1: "TBA",
    team2: "TBA",
    team1Goals: 0,
    team2Goals: 0,
    stadium: "Al Bayt Stadium",
  },
];

export const WC_2022_MATCH_SEED_THIRD_PLACE_PLAYOFF: WC2022ThirdPlaceMatch = {
  matchNumber: 63,
  round: "Third Place Playoff",
  potentialTeam1: "L61",
  potentialTeam2: "L62",
  date: new Date("2022 11 17"),
  team1: "TBA",
  team2: "TBA",
  team1Goals: 0,
  team2Goals: 0,
  stadium: "Khalifa International Stadium",
};

export const WC_2022_MATCH_SEED_FINAL: WC2022FinalMatch = {
  matchNumber: 64,
  round: "Final",
  potentialTeam1: "W61",
  potentialTeam2: "W62",
  date: new Date("2022 11 18"),
  team1: "TBA",
  team2: "TBA",
  team1Goals: 0,
  team2Goals: 0,
  stadium: "Lusail Stadium",
};
