// TODO: Fix and then use Match interface in /models
const WC_2022_MATCH_SEEDS_GROUP_STAGE = [
  {
    match: 1,
    date: new Date("20 November 2022"),
    team1: "Qatar",
    team2: "Ecuador",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "England",
    team2: "Iran",
    group: "B",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
  {
    match: 2,
    date: new Date("21 November 2022"),
    team1: "Senegal",
    team2: "Netherlands",
    group: "A",
    flag: "",
  },
];

export default WC_2022_MATCH_SEEDS_GROUP_STAGE;
